spring:
  # AWS RDS(PostgreSQL) 관련 설정
  # EC2에 역할 부여를 하더라도 해당 값은 반드시 들어가야 합니다.
  datasource:
    url: jdbc:postgresql://${AWS_RDS_ENDPOINT}:${AWS_RDS_PORT}/${AWS_RDS_DB_NAME}
    username: ${AWS_RDS_USERNAME}
    password: ${PASSWORD_1}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    # 성능 향상을 위해 설정을 끕니다
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
#    hikari:
#      maximum-pool-size: 80 # RDS 최대 커넥션 풀 ()
#      minimum-idle: 2 # 최소 보장 가능한 커넥션 수
#      idle-timeout: 600000 # 커넥션이 유휴 상태로 유지되는 최대 시간 (10분)
#      max-lifetime: 1200000 # 커넥션의 최대 수명 (20분)
#      connection-timeout: 30000 # 커넥션을 얻기 위해 대기하는 최대 시간 (30초)
#      leak-detection-threshold: 60000 # 커넥션 누수 감지 임계값 (60초)
#      pool-name: HikariCP-Production

logging:
  level:
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN
    org.springframework.security.oauth2: INFO
    org.springframework.security.web: INFO
    com.back: INFO