spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: jdbc:h2:mem:db_test;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver